### ISSUE TITLE
CSVJSON Parser in Ruby (in the public domain)

### ISSUE THREAD

**Issue by geraldb** [DrorHarari/csvjson.github.io#6]
Hello,
   Thanks for the write-up and the fantastic idea. Your format inspired the new CSV <3 JSON format <https://github.com/csvspecs/csv-json> (it differs by including comments and by restricting headers and so on.

Anyways, here's a working CSVJSON parser in ruby (it's public domain), use it as you please:

```` ruby
require 'pp'
require 'json'
require 'stringio'

  class CsvJson

   include Enumerable

    def initialize( data )
       if data.is_a?( String )
          @input = data   # note: just needs each for each_line
      else  ## assume io
          @input = data
      end
    end

    def each( &block )
      @input.each_line do |line|
        ##  note: chomp('') if is an empty string,
        ##    it will remove all trailing newlines from the string.
        line = line.chomp( '' )

        next if line.empty?             ## skip blank lines
        
        ## note: auto-wrap in array e.g. with []
        json = JSON.parse( "[#{line}]" )
        block.call( json )
      end
    end
  end # class CsvJson
````

And use like:

````ruby
csv = CsvJson.new( <<TXT )     # from a string
1,"John","12 Totem Rd. Aspen",true
2,"Bob",null,false
3,"Sue","Bigsby, 345 Carnival, WA 23009",false
TXT

# -or-
csv = CsvJson.new(  File.open( "test.csvj" ) )   # from a file (io)


table = csv.to_a
puts
puts "data:"
pp table
````

will print:

```
data:
[[1, "John", "12 Totem Rd. Aspen", true],
 [2, "Bob", nil, false],
 [3, "Sue", "Bigsby, 345 Carnival, WA 23009", false]]
````

All the best. Keep it up. Cheers. Prost.

**Comment by DrorHarari** [comment]
Thanks for the comment @geraldb - the original JSON syntax did not include comments and so I did not refer to them when relying on JSON to guide the 'right' way to write CSVJSON files -- priority one for me is to have the base line as simple as possible. There is no well defined or agreed upon semantics for comment lines in CSV - it is a worthy discussion but at most tangential to the format itself.

In your proposal, there is significant emphasis on clarity or readability for humans.  I have nothing against humans 8-) but CSVJSON, being a CSV variant, has enough clarity for humans, it should be great for software agents, easy to consume, produce and implement. 

/d

**Comment by geraldb** [comment]
Again thanks for the write-up and the fantastic idea. Happy to see blank lines included in CSVJSON :-).  In the CSV world the most used comment marker is the hash-mark `#` and, that is, the "unix" heritage (all shells, all scripting languages, etc.) use a '#'. A format without comments in my humble opinion is only for machines (not humans). 
PS: If you add one day comments, here's the line (in code) for the parser (in ruby) :-) : 

     next if line.start_with?( "#" )   ## skip comment lines

PPS: Again thanks for the great CSVJSON format and putting it all together with a website, repo, etc.

**Comment by DrorHarari** [comment]
Hi @geraldb  - sorry for the late reply...

Supporting comments can be a feature of the parser even if the formal definition does not support it. That is the case, for example, with JSON. 

The main reason why I don't think it should be in the format definition is that it would make implementation of the formal spec more complex -- with the bare-bone definition, one can simply read in a line, wrap it with '[' and ']' and it's a valid JSON to be parsed.

As for blank lines, I'll take a look in the latest RFC for the CSV format and take a hint from there.

Thanks again for the feedback.

/d

**Comment by geraldb** [comment]
@DrorHarari  No worries. Thanks for the fantastic format and write-up and initiative. The point of the issue / ticket was NOT to make you (or consider to) change the format. I see your points. The point was to highlight the new  working CSVJSON parser in ruby (see above)- (I think it's also written in the ticket title :-)) - that's the fantastic part - the format is "easy" to read / parse (if there's a json parser).  Thanks again. Have a great weekend. Keep it up. Cheers. Prost. PS: I was just "house cleaning" and closing half a dozen of open issues on github over the years. Sorry for any confusion (was not "complaining" about not getting an answer. Thanks again).
