### ISSUE TITLE
Empty, trailing rows in a file are converted to json with null property values.

### ISSUE THREAD

**Issue by mkomisin** [DrorHarari/csvjson.github.io#7]
When converting CSV or Tab-delimited files to JSON, empty rows at the end of a file cause a single entry of null-valued properties to be created, e.g. ,  {    "name": null,    "TITLE": null,    "ARTIST": null,    "COUNTRY": null,    "COMPANY": null,    "PRICE": null,    "YEAR": null  }

**Comment by DrorHarari** [comment]
There is no software currently on this repository - you must have meant to comment on another repository.
